CREATE TYPE "public"."order_status" AS ENUM('PENDING', 'COMPLETED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."purchase_order_status" AS ENUM('DRAFT', 'ORDERED', 'RECEIVED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."shift_status" AS ENUM('OPEN', 'CLOSED');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('ADMIN', 'MANAGER', 'CASHIER');--> statement-breakpoint
CREATE TABLE "alswap-inventory_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "alswap-inventory_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alswap-inventory_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tenantId" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_customer" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"tenantId" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"email" varchar(255),
	"phone" varchar(255),
	"loyaltyPoints" integer DEFAULT 0,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_order_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alswap-inventory_order_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"orderId" varchar(255) NOT NULL,
	"productId" varchar(255) NOT NULL,
	"quantity" integer NOT NULL,
	"price" numeric(10, 2) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_order" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"tenantId" varchar(255) NOT NULL,
	"shiftId" varchar(255),
	"customerId" varchar(255),
	"total_amount" numeric(10, 2) NOT NULL,
	"status" "order_status" DEFAULT 'COMPLETED' NOT NULL,
	"paymentMethod" varchar(50) DEFAULT 'CASH',
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_product" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"tenantId" varchar(255) NOT NULL,
	"categoryId" integer,
	"supplierId" varchar(255),
	"name" varchar(255) NOT NULL,
	"image" varchar(255),
	"barcode" varchar(255),
	"sku" varchar(255),
	"price" numeric(10, 2) NOT NULL,
	"cost_price" numeric(10, 2),
	"stockQuantity" integer DEFAULT 0 NOT NULL,
	"lowStockThreshold" integer DEFAULT 5,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_purchase_order_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alswap-inventory_purchase_order_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"purchaseOrderId" varchar(255) NOT NULL,
	"productId" varchar(255) NOT NULL,
	"quantity" integer NOT NULL,
	"unit_cost" numeric(10, 2),
	"receivedQuantity" integer DEFAULT 0
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_purchase_order" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"tenantId" varchar(255) NOT NULL,
	"supplierId" varchar(255),
	"status" "purchase_order_status" DEFAULT 'DRAFT' NOT NULL,
	"total_amount" numeric(10, 2) DEFAULT '0',
	"expectedDate" timestamp with time zone,
	"receivedDate" timestamp with time zone,
	"notes" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_shift" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"tenantId" varchar(255) NOT NULL,
	"userId" varchar(255) NOT NULL,
	"startTime" timestamp with time zone DEFAULT now() NOT NULL,
	"endTime" timestamp with time zone,
	"start_cash" numeric(10, 2) DEFAULT '0',
	"end_cash" numeric(10, 2),
	"status" "shift_status" DEFAULT 'OPEN' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_supplier" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"tenantId" varchar(255) NOT NULL,
	"name" varchar(255) NOT NULL,
	"contactPerson" varchar(255),
	"email" varchar(255),
	"phone" varchar(255),
	"address" text,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_tenant" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"slug" varchar(255) NOT NULL,
	"logo" varchar(255),
	"brandColor" varchar(50) DEFAULT '#000000',
	"primary_color_light" varchar(50) DEFAULT '#9333EA',
	"primary_color_dark" varchar(50) DEFAULT '#A855F7',
	"currency" varchar(10) DEFAULT '₦',
	"location" varchar(255),
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "alswap-inventory_tenant_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"tenantId" varchar(255),
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"emailVerified" timestamp with time zone,
	"password" varchar(255),
	"image" varchar(255),
	"role" "user_role" DEFAULT 'CASHIER'
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "alswap-inventory_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "alswap-inventory_account" ADD CONSTRAINT "alswap-inventory_account_userId_alswap-inventory_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."alswap-inventory_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_category" ADD CONSTRAINT "alswap-inventory_category_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_customer" ADD CONSTRAINT "alswap-inventory_customer_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_order_item" ADD CONSTRAINT "alswap-inventory_order_item_orderId_alswap-inventory_order_id_fk" FOREIGN KEY ("orderId") REFERENCES "public"."alswap-inventory_order"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_order_item" ADD CONSTRAINT "alswap-inventory_order_item_productId_alswap-inventory_product_id_fk" FOREIGN KEY ("productId") REFERENCES "public"."alswap-inventory_product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_order" ADD CONSTRAINT "alswap-inventory_order_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_order" ADD CONSTRAINT "alswap-inventory_order_shiftId_alswap-inventory_shift_id_fk" FOREIGN KEY ("shiftId") REFERENCES "public"."alswap-inventory_shift"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_order" ADD CONSTRAINT "alswap-inventory_order_customerId_alswap-inventory_customer_id_fk" FOREIGN KEY ("customerId") REFERENCES "public"."alswap-inventory_customer"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_product" ADD CONSTRAINT "alswap-inventory_product_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_product" ADD CONSTRAINT "alswap-inventory_product_categoryId_alswap-inventory_category_id_fk" FOREIGN KEY ("categoryId") REFERENCES "public"."alswap-inventory_category"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_product" ADD CONSTRAINT "alswap-inventory_product_supplierId_alswap-inventory_supplier_id_fk" FOREIGN KEY ("supplierId") REFERENCES "public"."alswap-inventory_supplier"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_purchase_order_item" ADD CONSTRAINT "alswap-inventory_purchase_order_item_purchaseOrderId_alswap-inventory_purchase_order_id_fk" FOREIGN KEY ("purchaseOrderId") REFERENCES "public"."alswap-inventory_purchase_order"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_purchase_order_item" ADD CONSTRAINT "alswap-inventory_purchase_order_item_productId_alswap-inventory_product_id_fk" FOREIGN KEY ("productId") REFERENCES "public"."alswap-inventory_product"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_purchase_order" ADD CONSTRAINT "alswap-inventory_purchase_order_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_purchase_order" ADD CONSTRAINT "alswap-inventory_purchase_order_supplierId_alswap-inventory_supplier_id_fk" FOREIGN KEY ("supplierId") REFERENCES "public"."alswap-inventory_supplier"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_session" ADD CONSTRAINT "alswap-inventory_session_userId_alswap-inventory_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."alswap-inventory_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_shift" ADD CONSTRAINT "alswap-inventory_shift_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_shift" ADD CONSTRAINT "alswap-inventory_shift_userId_alswap-inventory_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."alswap-inventory_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_supplier" ADD CONSTRAINT "alswap-inventory_supplier_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_user" ADD CONSTRAINT "alswap-inventory_user_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "alswap-inventory_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "category_tenant_idx" ON "alswap-inventory_category" USING btree ("tenantId");--> statement-breakpoint
CREATE INDEX "customer_tenant_idx" ON "alswap-inventory_customer" USING btree ("tenantId");--> statement-breakpoint
CREATE INDEX "order_tenant_idx" ON "alswap-inventory_order" USING btree ("tenantId");--> statement-breakpoint
CREATE INDEX "product_tenant_idx" ON "alswap-inventory_product" USING btree ("tenantId");--> statement-breakpoint
CREATE INDEX "product_barcode_idx" ON "alswap-inventory_product" USING btree ("barcode");--> statement-breakpoint
CREATE INDEX "po_tenant_idx" ON "alswap-inventory_purchase_order" USING btree ("tenantId");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "alswap-inventory_session" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "shift_tenant_idx" ON "alswap-inventory_shift" USING btree ("tenantId");--> statement-breakpoint
CREATE INDEX "supplier_tenant_idx" ON "alswap-inventory_supplier" USING btree ("tenantId");--> statement-breakpoint
CREATE INDEX "tenant_slug_idx" ON "alswap-inventory_tenant" USING btree ("slug");