CREATE TYPE "public"."trend_run_status" AS ENUM('OK', 'PARTIAL', 'BLOCKED', 'FAILED');--> statement-breakpoint
CREATE TYPE "public"."trend_term_kind" AS ENUM('ANCHOR', 'COMPARE', 'SEED');--> statement-breakpoint
CREATE TABLE "alswap-inventory_search_query_daily" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alswap-inventory_search_query_daily_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tenantId" varchar(255) NOT NULL,
	"term" varchar(80) NOT NULL,
	"day" date NOT NULL,
	"searches" integer DEFAULT 0 NOT NULL,
	"zero_result_searches" integer DEFAULT 0 NOT NULL,
	"last_result_count" integer DEFAULT 0 NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_trend_run" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alswap-inventory_trend_run_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tenantId" varchar(255) NOT NULL,
	"trigger" varchar(16) NOT NULL,
	"status" "trend_run_status" NOT NULL,
	"requests_made" integer DEFAULT 0 NOT NULL,
	"terms_updated" integer DEFAULT 0 NOT NULL,
	"error" text,
	"started_at" timestamp with time zone NOT NULL,
	"finished_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_trend_snapshot" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alswap-inventory_trend_snapshot_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tenantId" varchar(255) NOT NULL,
	"term_id" integer NOT NULL,
	"year_score" real,
	"recent_score" real,
	"series" json,
	"related" json,
	"fetched_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alswap-inventory_trend_term" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alswap-inventory_trend_term_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tenantId" varchar(255) NOT NULL,
	"term" varchar(100) NOT NULL,
	"geo" varchar(16) NOT NULL,
	"kind" "trend_term_kind" NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"last_fetched_at" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "alswap-inventory_search_query_daily" ADD CONSTRAINT "alswap-inventory_search_query_daily_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_trend_run" ADD CONSTRAINT "alswap-inventory_trend_run_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_trend_snapshot" ADD CONSTRAINT "alswap-inventory_trend_snapshot_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_trend_snapshot" ADD CONSTRAINT "alswap-inventory_trend_snapshot_term_id_alswap-inventory_trend_term_id_fk" FOREIGN KEY ("term_id") REFERENCES "public"."alswap-inventory_trend_term"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alswap-inventory_trend_term" ADD CONSTRAINT "alswap-inventory_trend_term_tenantId_alswap-inventory_tenant_id_fk" FOREIGN KEY ("tenantId") REFERENCES "public"."alswap-inventory_tenant"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "search_query_daily_tenant_term_day_idx" ON "alswap-inventory_search_query_daily" USING btree ("tenantId","term","day");--> statement-breakpoint
CREATE INDEX "search_query_daily_tenant_day_idx" ON "alswap-inventory_search_query_daily" USING btree ("tenantId","day");--> statement-breakpoint
CREATE INDEX "trend_run_tenant_started_idx" ON "alswap-inventory_trend_run" USING btree ("tenantId","started_at");--> statement-breakpoint
CREATE INDEX "trend_snapshot_term_fetched_idx" ON "alswap-inventory_trend_snapshot" USING btree ("term_id","fetched_at");--> statement-breakpoint
CREATE UNIQUE INDEX "trend_term_tenant_term_geo_kind_idx" ON "alswap-inventory_trend_term" USING btree ("tenantId","term","geo","kind");